version: '3'

services:
  client_service:
    build: ./client_service
    ports:
      - "8003:8003"
    depends_on:
      - database_service
      - business_service
    networks:
      - my_network

  database_service:
    build: ./database_service
    ports:
      - "8002:8002"
    networks:
      - my_network

  business_service:
    build: ./business_service
    ports:
      - "8001:8001"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
